// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace GooglePlayGames
{
public static class GPGConstant
{
        public const string achievement_gold_smasher = "CgkIj4_O2YYFEAIQEw"; // <GPGSID>
        public const string achievement_gold_frog_fragger = "CgkIj4_O2YYFEAIQFA"; // <GPGSID>
        public const string achievement_sliver_frog_champion = "CgkIj4_O2YYFEAIQEg"; // <GPGSID>
        public const string leaderboard_highest_level = "CgkIj4_O2YYFEAIQBg"; // <GPGSID>
        public const string achievement_sliver_frog_slayer = "CgkIj4_O2YYFEAIQEA"; // <GPGSID>
        public const string package_name = "com.carthagames.FrogSmash"; // <GPGSID>
        public const string achievement_gold_frog_champion = "CgkIj4_O2YYFEAIQFw"; // <GPGSID>
        public const string achievement_frog_slayer = "CgkIj4_O2YYFEAIQAw"; // <GPGSID>
        public const string achievement_bronze_frog_hunter = "CgkIj4_O2YYFEAIQDA"; // <GPGSID>
        public const string achievement_bronze_smasher = "CgkIj4_O2YYFEAIQCQ"; // <GPGSID>
        public const string achievement_sliver_frog_fragger = "CgkIj4_O2YYFEAIQDw"; // <GPGSID>
        public const string achievement_bronze_frog_champion = "CgkIj4_O2YYFEAIQDQ"; // <GPGSID>
        public const string achievement_bronze_frog_slayer = "CgkIj4_O2YYFEAIQCw"; // <GPGSID>
        public const string achievement_frog_champion = "CgkIj4_O2YYFEAIQBQ"; // <GPGSID>
        public const string achievement_frog_hunter = "CgkIj4_O2YYFEAIQBA"; // <GPGSID>
        public const string achievement_gold_frog_slayer = "CgkIj4_O2YYFEAIQFQ"; // <GPGSID>
        public const string achievement_smasher = "CgkIj4_O2YYFEAIQAQ"; // <GPGSID>
        public const string achievement_sliver_smasher = "CgkIj4_O2YYFEAIQDg"; // <GPGSID>
        public const string achievement_sliver_frog_hunter = "CgkIj4_O2YYFEAIQEQ"; // <GPGSID>
        public const string achievement_bronze_frog_fragger = "CgkIj4_O2YYFEAIQCg"; // <GPGSID>
        public const string achievement_gold_frog_hunter = "CgkIj4_O2YYFEAIQFg"; // <GPGSID>
        public const string achievement_frog_fragger = "CgkIj4_O2YYFEAIQAg"; // <GPGSID>
        public const string leaderboard_coins_frogs_farmers = "CgkIj4_O2YYFEAIQBw"; // <GPGSID>

}
}
